<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <base href="<?= BASE_URL ?>">

  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  <link rel="stylesheet" href="css/style.css">
  <title> Galeria de Arte Digital </title>
</head>

<body>

  <!-- main header -->
  <header>
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="home">Galeria de Arte</a>
        </ul>
      </div>
      <div>
      <?php if (isset($_SESSION['id_usuario'])): ?>
          <a href="<?= BASE_URL ?>logout">Cerrar sesión</a>
        <?php else: ?>
          <a href="<?= BASE_URL ?>login_form">Iniciar sesión</a>
        <?php endif; ?>
      </div>
    </nav>


    <!-- Botón hamburguesa -->
    <button id="menuBtn" onclick="abrirMenu()">☰</button>

    <!-- Overlay borroso -->
    <div id="menuOverlay" onclick="cerrarMenu()"></div>

    <!-- Menú lateral -->
    <div id="menuLateral">
      <div id="menuHeader">
        <span>MENÚ</span>
        <button onclick="cerrarMenu()">✕</button>
      </div>
      <nav>
        <a href="home">Inicio</a>
        <a href="obra">Obras</a>
        <a href="artista">Artistas</a>

        <?php if (isset($_SESSION['id_usuario'])): ?>
          <a href="<?= BASE_URL ?>addItem">Agregar obra</a>
          <a href="<?= BASE_URL ?>AddCategory">Agregar artista</a>
        <?php endif; ?>
        
      </nav>
      <footer>GALERÍA DE ARTE © 2026</footer>
    </div>


    </div>
    </div>
    </div>
    </div>
  </header>