<?php require __DIR__ . '/layout/header.phtml' ?>

<main class="container mt-4">

    <div class="card h-100">
        <div class="card-header bg-primary text-white">
            <h5 class="mb-0">Iniciar sesión</h5>
        </div>
        <div class="card-body">
            <form method="POST" action="login">
                <div class="mb-3">
                    <label class="form-label">E-mail <span class="text-danger">*</span></label>
                    <input required name="email" type="text" class="form-control" placeholder="Ingrese su email">
                </div>
                <div class="mb-3">
                    <label class="form-label">Contraseña <span class="text-danger">*</span></label>
                    <input required name="password" type="password" class="form-control" placeholder="******">
                </div>

                <div class="d-flex gap-2">
                    <button type="submit" class="btn btn-primary">Iniciar sesión</button>
                    <button type="reset" class="btn btn-outline-secondary">Limpiar</button>
                </div>
            </form>
        </div>
    </div>

</main>

<?php require __DIR__ . '/layout/footer.phtml' ?>